/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Color;

/**
 *
 * @author alboncho
 */
public class BuscarCliente extends javax.swing.JFrame {
   
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BuscarCliente.class.getName());

   /**
    * Creates new form BuscarCliente
    */
   public BuscarCliente() {
      initComponents();
      jMenuBar1.setOpaque(true);
      jMenuBar1.setOpaque(true);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jMenuItem2 = new javax.swing.JMenuItem();
      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jPanel2 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      tf_ci_cliente = new javax.swing.JTextField();
      btn_buscar_cliente = new javax.swing.JButton();
      jPanel3 = new javax.swing.JPanel();
      ta_remitente = new javax.swing.JTextArea();
      ta_bus = new javax.swing.JTextArea();
      ta_destinatario = new javax.swing.JTextArea();
      jPanel4 = new javax.swing.JPanel();
      jPanel5 = new javax.swing.JPanel();
      jPanel6 = new javax.swing.JPanel();
      jPanel7 = new javax.swing.JPanel();
      ta_bus1 = new javax.swing.JTextArea();
      jMenuBar1 = new javax.swing.JMenuBar();
      mn_inicio = new javax.swing.JMenu();
      menu_inicio = new javax.swing.JMenuItem();
      mn_buscar_cliente = new javax.swing.JMenu();
      jMenuItem3 = new javax.swing.JMenuItem();
      mn_ver_buses = new javax.swing.JMenu();
      jMenuItem1 = new javax.swing.JMenuItem();
      menu_destinos = new javax.swing.JMenu();
      menu_ver_destinos = new javax.swing.JMenuItem();
      menu_destinos1 = new javax.swing.JMenu();
      menu_entregas = new javax.swing.JMenuItem();
      jMenu1 = new javax.swing.JMenu();

      jMenuItem2.setText("jMenuItem2");

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jPanel1.setBackground(new java.awt.Color(51, 51, 51));

      jLabel1.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(128, 255, 128));
      jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lupa.png"))); // NOI18N
      jLabel1.setText("Buscar cliente");

      jPanel2.setBackground(new java.awt.Color(110, 97, 179));

      jLabel2.setForeground(new java.awt.Color(255, 255, 255));
      jLabel2.setText("C.I. Cliente:");

      tf_ci_cliente.addActionListener(this::tf_ci_clienteActionPerformed);

      btn_buscar_cliente.setBackground(new java.awt.Color(128, 255, 128));
      btn_buscar_cliente.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      btn_buscar_cliente.setForeground(new java.awt.Color(51, 51, 51));
      btn_buscar_cliente.setText("Buscar");
      btn_buscar_cliente.addActionListener(this::btn_buscar_clienteActionPerformed);

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tf_ci_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_buscar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(17, Short.MAX_VALUE))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
               .addComponent(tf_ci_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(13, 13, 13)
            .addComponent(btn_buscar_cliente)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      jPanel3.setBackground(new java.awt.Color(255, 255, 255));

      ta_remitente.setBackground(new java.awt.Color(255, 255, 255));
      ta_remitente.setColumns(20);
      ta_remitente.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
      ta_remitente.setForeground(new java.awt.Color(51, 51, 51));
      ta_remitente.setRows(5);
      ta_remitente.setText("Remitente:\n\nNombre: Juan Perez\nc.i.: 1234234\nCelular: 645345");

      ta_bus.setBackground(new java.awt.Color(255, 255, 255));
      ta_bus.setColumns(20);
      ta_bus.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
      ta_bus.setForeground(new java.awt.Color(51, 51, 51));
      ta_bus.setRows(5);
      ta_bus.setText("Encomienda:\n\nCodigo: 234-3\nDestino: Cochabamba\nPeso: 24kg\nEstado: entregado\nFecha: 24/2_2026\nDescipcion: \"\"\n");

      ta_destinatario.setBackground(new java.awt.Color(255, 255, 255));
      ta_destinatario.setColumns(20);
      ta_destinatario.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
      ta_destinatario.setForeground(new java.awt.Color(51, 51, 51));
      ta_destinatario.setRows(5);
      ta_destinatario.setText("Destinatario:\n\nNombre: Juan Perez\nc.i.: 1234234\nCelular: 645345");

      jPanel4.setBackground(new java.awt.Color(110, 97, 179));

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 7, Short.MAX_VALUE)
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 78, Short.MAX_VALUE)
      );

      jPanel5.setBackground(new java.awt.Color(110, 97, 179));

      javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
      jPanel5.setLayout(jPanel5Layout);
      jPanel5Layout.setHorizontalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 7, Short.MAX_VALUE)
      );
      jPanel5Layout.setVerticalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 77, Short.MAX_VALUE)
      );

      jPanel6.setBackground(new java.awt.Color(255, 153, 51));

      javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
      jPanel6.setLayout(jPanel6Layout);
      jPanel6Layout.setHorizontalGroup(
         jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 7, Short.MAX_VALUE)
      );
      jPanel6Layout.setVerticalGroup(
         jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 0, Short.MAX_VALUE)
      );

      jPanel7.setBackground(new java.awt.Color(255, 153, 51));

      javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
      jPanel7.setLayout(jPanel7Layout);
      jPanel7Layout.setHorizontalGroup(
         jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 7, Short.MAX_VALUE)
      );
      jPanel7Layout.setVerticalGroup(
         jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 75, Short.MAX_VALUE)
      );

      ta_bus1.setBackground(new java.awt.Color(255, 255, 255));
      ta_bus1.setColumns(20);
      ta_bus1.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
      ta_bus1.setForeground(new java.awt.Color(51, 51, 51));
      ta_bus1.setRows(5);
      ta_bus1.setText("Bus asignado:\n\nPlaca: 343-43\nHora de salida: 13:34\nCapacidad: 34kg");

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(ta_bus1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ta_remitente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ta_destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(ta_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(ta_remitente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(16, 16, 16)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(ta_destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ta_bus1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(ta_bus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                  .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGap(0, 36, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(57, 57, 57)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(51, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(53, Short.MAX_VALUE))
      );

      jMenuBar1.setBackground(new java.awt.Color(110, 97, 179));

      mn_inicio.setBackground(new java.awt.Color(110, 97, 179));
      mn_inicio.setForeground(new java.awt.Color(255, 255, 255));
      mn_inicio.setText("Inicio");
      mn_inicio.setBorderPainted(false);
      mn_inicio.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      mn_inicio.setHideActionText(true);
      mn_inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      mn_inicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      mn_inicio.setIconTextGap(13);
      mn_inicio.setMaximumSize(new java.awt.Dimension(70, 32767));
      mn_inicio.setMinimumSize(new java.awt.Dimension(60, 40));
      mn_inicio.setPreferredSize(new java.awt.Dimension(70, 28));

      menu_inicio.setText("Inicio");
      menu_inicio.addActionListener(this::menu_inicioActionPerformed);
      mn_inicio.add(menu_inicio);

      jMenuBar1.add(mn_inicio);

      mn_buscar_cliente.setBackground(new java.awt.Color(110, 97, 179));
      mn_buscar_cliente.setForeground(new java.awt.Color(255, 255, 255));
      mn_buscar_cliente.setText("Cliente");
      mn_buscar_cliente.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      mn_buscar_cliente.setHideActionText(true);
      mn_buscar_cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      mn_buscar_cliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      mn_buscar_cliente.setIconTextGap(9);
      mn_buscar_cliente.setMaximumSize(new java.awt.Dimension(70, 32767));
      mn_buscar_cliente.setMinimumSize(new java.awt.Dimension(60, 40));
      mn_buscar_cliente.setPreferredSize(new java.awt.Dimension(70, 28));

      jMenuItem3.setText("Buscar Cliente");
      jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
      mn_buscar_cliente.add(jMenuItem3);

      jMenuBar1.add(mn_buscar_cliente);

      mn_ver_buses.setBackground(new java.awt.Color(110, 97, 179));
      mn_ver_buses.setForeground(new java.awt.Color(255, 255, 255));
      mn_ver_buses.setText("Buses");
      mn_ver_buses.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      mn_ver_buses.setHideActionText(true);
      mn_ver_buses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      mn_ver_buses.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      mn_ver_buses.setIconTextGap(13);
      mn_ver_buses.setMaximumSize(new java.awt.Dimension(70, 32767));
      mn_ver_buses.setMinimumSize(new java.awt.Dimension(60, 40));
      mn_ver_buses.setPreferredSize(new java.awt.Dimension(70, 28));

      jMenuItem1.setText("Ver buses");
      jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
      mn_ver_buses.add(jMenuItem1);

      jMenuBar1.add(mn_ver_buses);

      menu_destinos.setBackground(new java.awt.Color(110, 97, 179));
      menu_destinos.setForeground(new java.awt.Color(255, 255, 255));
      menu_destinos.setText("Destinos");
      menu_destinos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      menu_destinos.setHideActionText(true);
      menu_destinos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      menu_destinos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      menu_destinos.setIconTextGap(13);
      menu_destinos.setMaximumSize(new java.awt.Dimension(88, 32767));
      menu_destinos.setMinimumSize(new java.awt.Dimension(60, 40));
      menu_destinos.setPreferredSize(new java.awt.Dimension(70, 28));

      menu_ver_destinos.setText("Ver destinos");
      menu_ver_destinos.addActionListener(this::menu_ver_destinosActionPerformed);
      menu_destinos.add(menu_ver_destinos);

      jMenuBar1.add(menu_destinos);

      menu_destinos1.setBackground(new java.awt.Color(110, 97, 179));
      menu_destinos1.setForeground(new java.awt.Color(255, 255, 255));
      menu_destinos1.setText("Entregas");
      menu_destinos1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      menu_destinos1.setHideActionText(true);
      menu_destinos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      menu_destinos1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      menu_destinos1.setIconTextGap(13);
      menu_destinos1.setMaximumSize(new java.awt.Dimension(88, 32767));
      menu_destinos1.setMinimumSize(new java.awt.Dimension(60, 40));
      menu_destinos1.setPreferredSize(new java.awt.Dimension(70, 28));

      menu_entregas.setText("Ver entregas");
      menu_entregas.addActionListener(this::menu_entregasActionPerformed);
      menu_destinos1.add(menu_entregas);

      jMenuBar1.add(menu_destinos1);

      jMenu1.setBackground(new java.awt.Color(110, 97, 179));
      jMenu1.setMaximumSize(new java.awt.Dimension(310, 32767));
      jMenuBar1.add(jMenu1);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void tf_ci_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ci_clienteActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_tf_ci_clienteActionPerformed

   private void btn_buscar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_clienteActionPerformed
      int ci = Integer.parseInt(tf_ci_cliente.getText());
      
      // METODO BUSCAR CLIENTE 
      // ...
      
      String nombre = "encontrado";
      String celular = "encontrado";
      String encomienda = "encontrado";
      
      ta_remitente.setText("Remitente:\n\nNombre: " + nombre + "\nCelular: " + celular + "\nC.I.: " + ci);
   }//GEN-LAST:event_btn_buscar_clienteActionPerformed

   private void menu_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_inicioActionPerformed
      Inicio inicio = new Inicio();
      inicio.setVisible(true);
      inicio.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_menu_inicioActionPerformed

   private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      BuscarCliente bc = new BuscarCliente();
      bc.setVisible(true);
      bc.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_jMenuItem3ActionPerformed

   private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      Buses buses = new Buses();
      buses.setVisible(true);
      buses.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_jMenuItem1ActionPerformed

   private void menu_ver_destinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ver_destinosActionPerformed
      Destinos destino = new Destinos();
      destino.setVisible(true);
      destino.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_menu_ver_destinosActionPerformed

   private void menu_entregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_entregasActionPerformed
      Entregas entregas = new Entregas();
      entregas.setVisible(true);
      entregas.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_menu_entregasActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btn_buscar_cliente;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JMenuItem jMenuItem1;
   private javax.swing.JMenuItem jMenuItem2;
   private javax.swing.JMenuItem jMenuItem3;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JPanel jPanel6;
   private javax.swing.JPanel jPanel7;
   private javax.swing.JMenu menu_destinos;
   private javax.swing.JMenu menu_destinos1;
   private javax.swing.JMenuItem menu_entregas;
   private javax.swing.JMenuItem menu_inicio;
   private javax.swing.JMenuItem menu_ver_destinos;
   private javax.swing.JMenu mn_buscar_cliente;
   private javax.swing.JMenu mn_inicio;
   private javax.swing.JMenu mn_ver_buses;
   private javax.swing.JTextArea ta_bus;
   private javax.swing.JTextArea ta_bus1;
   private javax.swing.JTextArea ta_destinatario;
   private javax.swing.JTextArea ta_remitente;
   private javax.swing.JTextField tf_ci_cliente;
   // End of variables declaration//GEN-END:variables
}
