/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author alboncho
 */
public class Buses extends javax.swing.JFrame {
   
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Buses.class.getName());

   /**
    * Creates new form Buses
    */
   public Buses() {
      initComponents();
      this.setLocationRelativeTo(null);
      jMenuBar1.setOpaque(true);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jMenuBar1 = new javax.swing.JMenuBar();
      mn_inicio = new javax.swing.JMenu();
      menu_inicio = new javax.swing.JMenuItem();
      mn_buscar_cliente = new javax.swing.JMenu();
      jMenuItem3 = new javax.swing.JMenuItem();
      mn_ver_buses = new javax.swing.JMenu();
      jMenuItem1 = new javax.swing.JMenuItem();
      jMenu1 = new javax.swing.JMenu();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 483, Short.MAX_VALUE)
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 530, Short.MAX_VALUE)
      );

      jMenuBar1.setBackground(new java.awt.Color(110, 97, 179));

      mn_inicio.setBackground(new java.awt.Color(110, 97, 179));
      mn_inicio.setForeground(new java.awt.Color(255, 255, 255));
      mn_inicio.setText("Inicio");
      mn_inicio.setBorderPainted(false);
      mn_inicio.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      mn_inicio.setHideActionText(true);
      mn_inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      mn_inicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      mn_inicio.setIconTextGap(13);
      mn_inicio.setMaximumSize(new java.awt.Dimension(70, 32767));
      mn_inicio.setMinimumSize(new java.awt.Dimension(60, 40));
      mn_inicio.setPreferredSize(new java.awt.Dimension(70, 28));

      menu_inicio.setText("Inicio");
      menu_inicio.addActionListener(this::menu_inicioActionPerformed);
      mn_inicio.add(menu_inicio);

      jMenuBar1.add(mn_inicio);

      mn_buscar_cliente.setBackground(new java.awt.Color(110, 97, 179));
      mn_buscar_cliente.setForeground(new java.awt.Color(255, 255, 255));
      mn_buscar_cliente.setText("Cliente");
      mn_buscar_cliente.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      mn_buscar_cliente.setHideActionText(true);
      mn_buscar_cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      mn_buscar_cliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      mn_buscar_cliente.setIconTextGap(9);
      mn_buscar_cliente.setMaximumSize(new java.awt.Dimension(70, 32767));
      mn_buscar_cliente.setMinimumSize(new java.awt.Dimension(60, 40));
      mn_buscar_cliente.setPreferredSize(new java.awt.Dimension(70, 28));

      jMenuItem3.setText("Buscar Cliente");
      jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
      mn_buscar_cliente.add(jMenuItem3);

      jMenuBar1.add(mn_buscar_cliente);

      mn_ver_buses.setBackground(new java.awt.Color(110, 97, 179));
      mn_ver_buses.setForeground(new java.awt.Color(255, 255, 255));
      mn_ver_buses.setText("Buses");
      mn_ver_buses.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      mn_ver_buses.setHideActionText(true);
      mn_ver_buses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      mn_ver_buses.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      mn_ver_buses.setIconTextGap(13);
      mn_ver_buses.setMaximumSize(new java.awt.Dimension(70, 32767));
      mn_ver_buses.setMinimumSize(new java.awt.Dimension(60, 40));
      mn_ver_buses.setPreferredSize(new java.awt.Dimension(70, 28));

      jMenuItem1.setText("Ver buses");
      mn_ver_buses.add(jMenuItem1);

      jMenuBar1.add(mn_ver_buses);

      jMenu1.setBackground(new java.awt.Color(110, 97, 179));
      jMenu1.setMaximumSize(new java.awt.Dimension(500, 32767));
      jMenuBar1.add(jMenu1);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      BuscarCliente bc = new BuscarCliente();
      bc.setVisible(true);
      bc.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_jMenuItem3ActionPerformed

   private void menu_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_inicioActionPerformed
      Inicio inicio = new Inicio();
      inicio.setVisible(true);
      inicio.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
      // TODO add your handling code here:
   }//GEN-LAST:event_menu_inicioActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
         logger.log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(() -> new Buses().setVisible(true));
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JMenuItem jMenuItem1;
   private javax.swing.JMenuItem jMenuItem3;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JMenuItem menu_inicio;
   private javax.swing.JMenu mn_buscar_cliente;
   private javax.swing.JMenu mn_inicio;
   private javax.swing.JMenu mn_ver_buses;
   // End of variables declaration//GEN-END:variables
}
