/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author alboncho
 */
public class Despachar extends javax.swing.JFrame {
   
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Despachar.class.getName());

   /**
    * Creates new form Despachar
    */
   public Despachar() {
      initComponents();
      jMenuBar1.setOpaque(true);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jPanel2 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      cb_destino = new javax.swing.JComboBox<>();
      jButton1 = new javax.swing.JButton();
      jMenuBar1 = new javax.swing.JMenuBar();
      mn_inicio = new javax.swing.JMenu();
      menu_inicio = new javax.swing.JMenuItem();
      mn_buscar_cliente = new javax.swing.JMenu();
      jMenuItem3 = new javax.swing.JMenuItem();
      jMenuItem2 = new javax.swing.JMenuItem();
      mn_ver_buses = new javax.swing.JMenu();
      jMenuItem1 = new javax.swing.JMenuItem();
      menu_despachar = new javax.swing.JMenuItem();
      menu_destinos = new javax.swing.JMenu();
      menu_ver_destinos = new javax.swing.JMenuItem();
      menu_destinos1 = new javax.swing.JMenu();
      menu_entregas = new javax.swing.JMenuItem();
      jMenu1 = new javax.swing.JMenu();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
      jLabel1.setText("Despachar Bus");

      jPanel2.setBackground(new java.awt.Color(51, 51, 51));

      jLabel2.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
      jLabel2.setText("Seleccionar destino:");

      cb_destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "La Paz", "Cochabamba", "Pando", "Santa Cruz", "Oruro", " " }));
      cb_destino.addActionListener(this::cb_destinoActionPerformed);

      jButton1.setBackground(new java.awt.Color(128, 255, 128));
      jButton1.setForeground(new java.awt.Color(51, 51, 51));
      jButton1.setText("Despachar");
      jButton1.addActionListener(this::jButton1ActionPerformed);

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(cb_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
            .addComponent(jButton1)
            .addContainerGap())
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(cb_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButton1))
            .addGap(17, 17, 17))
      );

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(jLabel1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addComponent(jLabel1)
            .addGap(18, 18, 18)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(43, Short.MAX_VALUE))
      );

      jMenuBar1.setBackground(new java.awt.Color(110, 97, 179));

      mn_inicio.setBackground(new java.awt.Color(110, 97, 179));
      mn_inicio.setForeground(new java.awt.Color(255, 255, 255));
      mn_inicio.setText("Inicio");
      mn_inicio.setBorderPainted(false);
      mn_inicio.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      mn_inicio.setHideActionText(true);
      mn_inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      mn_inicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      mn_inicio.setIconTextGap(13);
      mn_inicio.setMaximumSize(new java.awt.Dimension(70, 32767));
      mn_inicio.setMinimumSize(new java.awt.Dimension(60, 40));
      mn_inicio.setPreferredSize(new java.awt.Dimension(70, 28));

      menu_inicio.setText("Inicio");
      menu_inicio.addActionListener(this::menu_inicioActionPerformed);
      mn_inicio.add(menu_inicio);

      jMenuBar1.add(mn_inicio);

      mn_buscar_cliente.setBackground(new java.awt.Color(110, 97, 179));
      mn_buscar_cliente.setForeground(new java.awt.Color(255, 255, 255));
      mn_buscar_cliente.setText("Cliente");
      mn_buscar_cliente.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      mn_buscar_cliente.setHideActionText(true);
      mn_buscar_cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      mn_buscar_cliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      mn_buscar_cliente.setIconTextGap(9);
      mn_buscar_cliente.setMaximumSize(new java.awt.Dimension(70, 32767));
      mn_buscar_cliente.setMinimumSize(new java.awt.Dimension(60, 40));
      mn_buscar_cliente.setPreferredSize(new java.awt.Dimension(70, 28));

      jMenuItem3.setText("Buscar Cliente");
      jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
      mn_buscar_cliente.add(jMenuItem3);

      jMenuItem2.setText("Enc. pendientes");
      jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
      mn_buscar_cliente.add(jMenuItem2);

      jMenuBar1.add(mn_buscar_cliente);

      mn_ver_buses.setBackground(new java.awt.Color(110, 97, 179));
      mn_ver_buses.setForeground(new java.awt.Color(255, 255, 255));
      mn_ver_buses.setText("Buses");
      mn_ver_buses.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      mn_ver_buses.setHideActionText(true);
      mn_ver_buses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      mn_ver_buses.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      mn_ver_buses.setIconTextGap(13);
      mn_ver_buses.setMaximumSize(new java.awt.Dimension(70, 32767));
      mn_ver_buses.setMinimumSize(new java.awt.Dimension(60, 40));
      mn_ver_buses.setPreferredSize(new java.awt.Dimension(70, 28));

      jMenuItem1.setText("Ver buses");
      jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
      mn_ver_buses.add(jMenuItem1);

      menu_despachar.setText("Despachar");
      menu_despachar.addActionListener(this::menu_despacharActionPerformed);
      mn_ver_buses.add(menu_despachar);

      jMenuBar1.add(mn_ver_buses);

      menu_destinos.setBackground(new java.awt.Color(110, 97, 179));
      menu_destinos.setForeground(new java.awt.Color(255, 255, 255));
      menu_destinos.setText("Destinos");
      menu_destinos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      menu_destinos.setHideActionText(true);
      menu_destinos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      menu_destinos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      menu_destinos.setIconTextGap(13);
      menu_destinos.setMaximumSize(new java.awt.Dimension(88, 32767));
      menu_destinos.setMinimumSize(new java.awt.Dimension(60, 40));
      menu_destinos.setPreferredSize(new java.awt.Dimension(70, 28));

      menu_ver_destinos.setText("Ver destinos");
      menu_ver_destinos.addActionListener(this::menu_ver_destinosActionPerformed);
      menu_destinos.add(menu_ver_destinos);

      jMenuBar1.add(menu_destinos);

      menu_destinos1.setBackground(new java.awt.Color(110, 97, 179));
      menu_destinos1.setForeground(new java.awt.Color(255, 255, 255));
      menu_destinos1.setText("Entregas");
      menu_destinos1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      menu_destinos1.setHideActionText(true);
      menu_destinos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      menu_destinos1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      menu_destinos1.setIconTextGap(13);
      menu_destinos1.setMaximumSize(new java.awt.Dimension(88, 32767));
      menu_destinos1.setMinimumSize(new java.awt.Dimension(60, 40));
      menu_destinos1.setPreferredSize(new java.awt.Dimension(70, 28));

      menu_entregas.setText("Ver entregas");
      menu_entregas.addActionListener(this::menu_entregasActionPerformed);
      menu_destinos1.add(menu_entregas);

      jMenuBar1.add(menu_destinos1);

      jMenu1.setBackground(new java.awt.Color(110, 97, 179));
      jMenu1.setMaximumSize(new java.awt.Dimension(310, 32767));
      jMenuBar1.add(jMenu1);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void menu_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_inicioActionPerformed
      Inicio inicio = new Inicio();
      inicio.setVisible(true);
      inicio.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_menu_inicioActionPerformed

   private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      BuscarCliente bc = new BuscarCliente();
      bc.setVisible(true);
      bc.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_jMenuItem3ActionPerformed

   private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      Buses buses = new Buses();
      buses.setVisible(true);
      buses.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_jMenuItem1ActionPerformed

   private void menu_ver_destinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ver_destinosActionPerformed
      Destinos destino = new Destinos();
      destino.setVisible(true);
      destino.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_menu_ver_destinosActionPerformed

   private void menu_entregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_entregasActionPerformed
      Entregas entregas = new Entregas();
      entregas.setVisible(true);
      entregas.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_menu_entregasActionPerformed

   private void menu_despacharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_despacharActionPerformed

      Despachar despachar = new Despachar();
      despachar.setVisible(true);
      despachar.setLocationRelativeTo(null);
      // TODO add your handling code here:
   }//GEN-LAST:event_menu_despacharActionPerformed

   private void cb_destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_destinoActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_cb_destinoActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String destino = cb_destino.getSelectedItem().toString();
      
      System.out.println(destino);
   }//GEN-LAST:event_jButton1ActionPerformed

   private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      Pendiente pen = new Pendiente();
      pen.setVisible(true);
      pen.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_jMenuItem2ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
         logger.log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(() -> new Despachar().setVisible(true));
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox<String> cb_destino;
   private javax.swing.JButton jButton1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JMenuItem jMenuItem1;
   private javax.swing.JMenuItem jMenuItem2;
   private javax.swing.JMenuItem jMenuItem3;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JMenuItem menu_despachar;
   private javax.swing.JMenu menu_destinos;
   private javax.swing.JMenu menu_destinos1;
   private javax.swing.JMenuItem menu_entregas;
   private javax.swing.JMenuItem menu_inicio;
   private javax.swing.JMenuItem menu_ver_destinos;
   private javax.swing.JMenu mn_buscar_cliente;
   private javax.swing.JMenu mn_inicio;
   private javax.swing.JMenu mn_ver_buses;
   // End of variables declaration//GEN-END:variables
}
