/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import estructuras.PilaEntrega;
import javax.swing.table.DefaultTableModel;
import modelos.Entrega;
import persistencia.PersistenciaEntrega;

/**
 *
 * @author alboncho
 */
public class Historial extends javax.swing.JFrame {
   
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Historial.class.getName());

   /**
    * Creates new form HIstorial
    */
   public Historial() {
      initComponents();
      jMenuBar1.setOpaque(true);
      this.mostrarTabla();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jPanel4 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      tf_codigo = new javax.swing.JTextField();
      btn_ver_info = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      tabla_historial = new javax.swing.JTable();
      jScrollPane2 = new javax.swing.JScrollPane();
      ta_mas_info = new javax.swing.JTextArea();
      jMenuBar1 = new javax.swing.JMenuBar();
      mn_inicio = new javax.swing.JMenu();
      menu_inicio = new javax.swing.JMenuItem();
      mn_buscar_cliente = new javax.swing.JMenu();
      jMenuItem3 = new javax.swing.JMenuItem();
      jMenuItem2 = new javax.swing.JMenuItem();
      mn_ver_buses = new javax.swing.JMenu();
      jMenuItem1 = new javax.swing.JMenuItem();
      menu_despachar = new javax.swing.JMenuItem();
      menu_destinos = new javax.swing.JMenu();
      menu_ver_destinos = new javax.swing.JMenuItem();
      menu_destinos1 = new javax.swing.JMenu();
      menu_entregas = new javax.swing.JMenuItem();
      menu_historial = new javax.swing.JMenuItem();
      jMenu1 = new javax.swing.JMenu();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
      jLabel1.setText("Historial");

      jPanel4.setBackground(new java.awt.Color(51, 51, 51));

      jLabel2.setFont(new java.awt.Font("Cantarell", 1, 11)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(255, 51, 102));
      jLabel2.setText("Mas información");

      jLabel3.setText("Codigo:");

      tf_codigo.addActionListener(this::tf_codigoActionPerformed);

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel4Layout.createSequentialGroup()
                  .addComponent(jLabel2)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(jPanel4Layout.createSequentialGroup()
                  .addComponent(jLabel3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(tf_codigo)))
            .addContainerGap())
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
      );

      btn_ver_info.setBackground(new java.awt.Color(255, 102, 51));
      btn_ver_info.setForeground(new java.awt.Color(51, 51, 51));
      btn_ver_info.setText("Ver");
      btn_ver_info.addActionListener(this::btn_ver_infoActionPerformed);

      tabla_historial.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null},
            {null, null},
            {null, null},
            {null, null}
         },
         new String [] {
            "Codigo", "Fecha"
         }
      ));
      jScrollPane1.setViewportView(tabla_historial);

      ta_mas_info.setBackground(new java.awt.Color(0, 102, 102));
      ta_mas_info.setColumns(20);
      ta_mas_info.setRows(5);
      jScrollPane2.setViewportView(ta_mas_info);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(32, 32, 32)
                  .addComponent(jLabel1))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(27, 27, 27)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btn_ver_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(28, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addComponent(jLabel1)
            .addGap(33, 33, 33)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(12, 12, 12)
                  .addComponent(btn_ver_info)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(jScrollPane2))
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(39, Short.MAX_VALUE))
      );

      jMenuBar1.setBackground(new java.awt.Color(110, 97, 179));

      mn_inicio.setBackground(new java.awt.Color(110, 97, 179));
      mn_inicio.setForeground(new java.awt.Color(255, 255, 255));
      mn_inicio.setText("Inicio");
      mn_inicio.setBorderPainted(false);
      mn_inicio.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      mn_inicio.setHideActionText(true);
      mn_inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      mn_inicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      mn_inicio.setIconTextGap(13);
      mn_inicio.setMaximumSize(new java.awt.Dimension(70, 32767));
      mn_inicio.setMinimumSize(new java.awt.Dimension(60, 40));
      mn_inicio.setPreferredSize(new java.awt.Dimension(70, 28));

      menu_inicio.setText("Inicio");
      menu_inicio.addActionListener(this::menu_inicioActionPerformed);
      mn_inicio.add(menu_inicio);

      jMenuBar1.add(mn_inicio);

      mn_buscar_cliente.setBackground(new java.awt.Color(110, 97, 179));
      mn_buscar_cliente.setForeground(new java.awt.Color(255, 255, 255));
      mn_buscar_cliente.setText("Cliente");
      mn_buscar_cliente.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      mn_buscar_cliente.setHideActionText(true);
      mn_buscar_cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      mn_buscar_cliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      mn_buscar_cliente.setIconTextGap(9);
      mn_buscar_cliente.setMaximumSize(new java.awt.Dimension(70, 32767));
      mn_buscar_cliente.setMinimumSize(new java.awt.Dimension(60, 40));
      mn_buscar_cliente.setPreferredSize(new java.awt.Dimension(70, 28));

      jMenuItem3.setText("Buscar Cliente");
      jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
      mn_buscar_cliente.add(jMenuItem3);

      jMenuItem2.setText("Enc. Pendientes");
      jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
      mn_buscar_cliente.add(jMenuItem2);

      jMenuBar1.add(mn_buscar_cliente);

      mn_ver_buses.setBackground(new java.awt.Color(110, 97, 179));
      mn_ver_buses.setForeground(new java.awt.Color(255, 255, 255));
      mn_ver_buses.setText("Buses");
      mn_ver_buses.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      mn_ver_buses.setHideActionText(true);
      mn_ver_buses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      mn_ver_buses.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      mn_ver_buses.setIconTextGap(13);
      mn_ver_buses.setMaximumSize(new java.awt.Dimension(70, 32767));
      mn_ver_buses.setMinimumSize(new java.awt.Dimension(60, 40));
      mn_ver_buses.setPreferredSize(new java.awt.Dimension(70, 28));

      jMenuItem1.setText("Ver buses");
      jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
      mn_ver_buses.add(jMenuItem1);

      menu_despachar.setText("Despachar");
      menu_despachar.addActionListener(this::menu_despacharActionPerformed);
      mn_ver_buses.add(menu_despachar);

      jMenuBar1.add(mn_ver_buses);

      menu_destinos.setBackground(new java.awt.Color(110, 97, 179));
      menu_destinos.setForeground(new java.awt.Color(255, 255, 255));
      menu_destinos.setText("Destinos");
      menu_destinos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      menu_destinos.setHideActionText(true);
      menu_destinos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      menu_destinos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      menu_destinos.setIconTextGap(13);
      menu_destinos.setMaximumSize(new java.awt.Dimension(88, 32767));
      menu_destinos.setMinimumSize(new java.awt.Dimension(60, 40));
      menu_destinos.setPreferredSize(new java.awt.Dimension(70, 28));

      menu_ver_destinos.setText("Ver destinos");
      menu_ver_destinos.addActionListener(this::menu_ver_destinosActionPerformed);
      menu_destinos.add(menu_ver_destinos);

      jMenuBar1.add(menu_destinos);

      menu_destinos1.setBackground(new java.awt.Color(110, 97, 179));
      menu_destinos1.setForeground(new java.awt.Color(255, 255, 255));
      menu_destinos1.setText("Entregas");
      menu_destinos1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      menu_destinos1.setHideActionText(true);
      menu_destinos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      menu_destinos1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      menu_destinos1.setIconTextGap(13);
      menu_destinos1.setMaximumSize(new java.awt.Dimension(88, 32767));
      menu_destinos1.setMinimumSize(new java.awt.Dimension(60, 40));
      menu_destinos1.setPreferredSize(new java.awt.Dimension(70, 28));

      menu_entregas.setText("Registrar encomienda");
      menu_entregas.addActionListener(this::menu_entregasActionPerformed);
      menu_destinos1.add(menu_entregas);

      menu_historial.setText("Historial");
      menu_historial.addActionListener(this::menu_historialActionPerformed);
      menu_destinos1.add(menu_historial);

      jMenuBar1.add(menu_destinos1);

      jMenu1.setBackground(new java.awt.Color(110, 97, 179));
      jMenu1.setMaximumSize(new java.awt.Dimension(110, 32767));
      jMenuBar1.add(jMenu1);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void menu_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_inicioActionPerformed
      Inicio inicio = new Inicio();
      inicio.setVisible(true);
      inicio.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_menu_inicioActionPerformed

   private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      BuscarCliente bc = new BuscarCliente();
      bc.setVisible(true);
      bc.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_jMenuItem3ActionPerformed

   private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      Pendiente pen = new Pendiente();
      pen.setVisible(true);
      pen.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_jMenuItem2ActionPerformed

   private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      Buses buses = new Buses();
      buses.setVisible(true);
      buses.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_jMenuItem1ActionPerformed

   private void menu_despacharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_despacharActionPerformed
      Despachar despachar = new Despachar();
      despachar.setVisible(true);
      despachar.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_menu_despacharActionPerformed

   private void menu_ver_destinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ver_destinosActionPerformed
      Destinos destino = new Destinos();
      destino.setVisible(true);
      destino.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_menu_ver_destinosActionPerformed

   private void menu_entregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_entregasActionPerformed
      Entregas entregas = new Entregas();
      entregas.setVisible(true);
      entregas.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
   }//GEN-LAST:event_menu_entregasActionPerformed

   private void menu_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_historialActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_menu_historialActionPerformed

   private void tf_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoActionPerformed
         // TODO add your handling code here:
   }//GEN-LAST:event_tf_codigoActionPerformed

   private void btn_ver_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_infoActionPerformed
      String codigo = tf_codigo.getText();
      PilaEntrega pe = PersistenciaEntrega.cargar();
      
      if (pe == null) { pe = new PilaEntrega(); }
      
      PilaEntrega aux = new PilaEntrega();
      while (!pe.esVacia()) {
         Entrega e = pe.eli();
         
         if (String.valueOf(e.getCodEntrega()).equals(codigo)) {
            ta_mas_info.setText("Codigo: " + e.getCodEntrega() + "\nFecha de entrega: " + e.getFechaEntrega() + "\n\nEncomienda" + "\nCodigo: " + e.getEncomienda().getCodigo() + "\nDescripcion: " + e.getEncomienda().getDescripcion() + "\nPeso: " + e.getEncomienda().getPeso() + "\nDestino: " + e.getEncomienda().getDestino() + "\nEstado: " + e.getEncomienda().getEstado() + "\nFecha de registro: " + e.getEncomienda().getFechaRegistro() + "\n\nCliente remitente" + "\nNombre: " + e.getEncomienda().getRemitente().getNombre() + "\nC.I.: " + e.getEncomienda().getRemitente().getCi() + "\nCelular: " + e.getEncomienda().getRemitente().getCelular() + "\n\nCliente destinatario: " + "\nNombre: " + e.getEncomienda().getDestinatario().getNombre() + "\nC.I.: " + e.getEncomienda().getDestinatario().getCi() + "\nCelular: " + e.getEncomienda().getDestinatario().getCelular());
         }
      }

      // TODO add your handling code here:
   }//GEN-LAST:event_btn_ver_infoActionPerformed

   public void mostrarTabla() {
      PilaEntrega pe = PersistenciaEntrega.cargar();
      
      if (pe == null) { return; }
      
      DefaultTableModel modelo = (DefaultTableModel) tabla_historial.getModel();
      modelo.setRowCount(0);
      
      PilaEntrega aux = new PilaEntrega();
      while (!pe.esVacia()) {
         Entrega e = pe.eli();
         
         modelo.addRow(new Object[] {
            e.getCodEntrega(),
            e.getFechaEntrega()
         });
         
         aux.adi(e);
      }
      
      pe.vaciar(aux);  
   }
   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
         logger.log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(() -> new Historial().setVisible(true));
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btn_ver_info;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JMenuItem jMenuItem1;
   private javax.swing.JMenuItem jMenuItem2;
   private javax.swing.JMenuItem jMenuItem3;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JMenuItem menu_despachar;
   private javax.swing.JMenu menu_destinos;
   private javax.swing.JMenu menu_destinos1;
   private javax.swing.JMenuItem menu_entregas;
   private javax.swing.JMenuItem menu_historial;
   private javax.swing.JMenuItem menu_inicio;
   private javax.swing.JMenuItem menu_ver_destinos;
   private javax.swing.JMenu mn_buscar_cliente;
   private javax.swing.JMenu mn_inicio;
   private javax.swing.JMenu mn_ver_buses;
   private javax.swing.JTextArea ta_mas_info;
   private javax.swing.JTable tabla_historial;
   private javax.swing.JTextField tf_codigo;
   // End of variables declaration//GEN-END:variables
}
